name: Hourly hookzof Update

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  fetch-hookzof-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: create lookup
        run: |
          cd Lists/PROXY/hookzof_socks5
          python3 create_lookup_file.py

      - name: List files in the target directory
        run: ls -la Lists/PROXY/hookzof_socks5

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/PROXY/hookzof_socks5/*
          git commit -m "Update hourly hideip.me files" --allow-empty
          git push
