name: Hourly MuRongPIG Proxy checked Fetch

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  fetch-murongpig-proxies:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.x"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests

      - name: Fetch proxy list
        run: |
          cd Lists/PROXY/MuRongPIG_proxy_checked_list
          python3 fetch_proxy_list.py

      - name: List updated files
        run: ls -lah Lists/PROXY/MuRongPIG_proxy_checked_list

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/PROXY/MuRongPIG_proxy_checked_list/*
          git commit -m "Update hourly MuRongPIG proxy list" --allow-empty
          git push
