name: Hourly monosans_list Update

on:
  schedule:
    - cron: "0 * * * *" # Runs every hour
  workflow_dispatch:

jobs:
  fetch-monosans-files:
    runs-on: ubuntu-latest

    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Download all.txt File from monosans_list
        run: |
          # Define the target directory
          TARGET_DIR=Lists/PROXY/monosans_list
          mkdir -p $TARGET_DIR

          # List of .txt files to download
          FILES=(
            "all.txt"
          )

          # Base URL using raw.githubusercontent.com
          BASE_URL="https://raw.githubusercontent.com/monosans/proxy-list/refs/heads/main/proxies"

          # Download each file
          for FILE in "${FILES[@]}"; do
            echo "Downloading $FILE from $BASE_URL/$FILE"
            curl -L -o "$TARGET_DIR/$FILE" "$BASE_URL/$FILE" || echo "Failed to download $FILE"
          done

      - name: create lookup
        run: |
          pip install pandas 
          cd Lists/PROXY/monosans_list
          python3 create_lookup_file.py

      - name: List files in the target directory
        run: ls -la Lists/PROXY/monosans_list

      - name: Commit and Push results
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git pull
          git add Lists/PROXY/monosans_list/*
          git commit -m "Update hourly monosans_list files" --allow-empty
          git push
